---
keys:
  - &host_nas age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
  - &host_utility age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
  - &user_todd age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_todd
          - *host_nas
          - *host_utility
