---
keys:
  - &host_nas age15sdt0rda37qq3kxms29g5jcasqtcsz79ew99v4dvmes6jfjkvg8sgva5un
  - &host_dns1 age1yjppv3heup3m5pzgmakpgln9xxpc3wpn3fveqhjl9j8wqrnq7pnsv444fc
  - &user_todd age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_todd
          - *host_nas
          - *host_dns1
