---
keys:
  - &host_nas age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
  - &host_dns1 age1sr25smw8zytgmy50k5n753m93xx6mv783dxlp7rnfe6xdfe7tyjs4r0l2g
  - &host_dns2 age1ngz93hzfh3yj0zguxkrcm4j8zdtfmwn0khhez3yn0zj78pqajyss2netxy
  - &user_todd age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_todd
          - *host_nas
          - *host_dns1
          - *host_dns2
