# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.

{ pkgs }:

let
  vscode-utils = pkgs.vscode-utils;
in
{
  "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
    name = "python";
    publisher = "ms-python";
    version = "2023.25.10191009";
    sha256 = "068wvvzwrxw64v2zgxwq6cfc4li2nfgm2bb9zlnmalyf06xh6lk3";
  };

  "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-pylance";
    publisher = "ms-python";
    version = "2023.12.103";
    sha256 = "1lkh94vyx9k23yw7i6sl1yy5f5wf3kjm8c5ljybzvy1lbi831lyf";
  };

  "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "prettier-vscode";
    publisher = "esbenp";
    version = "10.1.0";
    sha256 = "01s0vi2h917mqfpdrhqhp2ijwkibw95yk2js0l587wvajbbry2s9";
  };

  "ms-azuretools"."vscode-docker" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-docker";
    publisher = "ms-azuretools";
    version = "1.28.0";
    sha256 = "0nmc3pdgxpmr6k2ksdczkv9bbwszncfczik0xjympqnd2k0ra9h0";
  };

  "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gitlens";
    publisher = "eamodio";
    version = "2024.1.1904";
    sha256 = "1vy5q7akrnxs3q4vhq1njbsbi8kysszl5yhpkns1q3z0kin6bw93";
  };

  "ms-vscode-remote"."remote-containers" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-containers";
    publisher = "ms-vscode-remote";
    version = "0.330.0";
    sha256 = "19a24fszhhc6d40r5r2kh5kvmpg0614p0666cdzci4nn5qr4bh3g";
  };

  "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-ssh";
    publisher = "ms-vscode-remote";
    version = "0.108.2023112915";
    sha256 = "1ys59dys5kmijr9f2afbzbwm7dx7ps78jdwp89q1kb4c0aajmkx2";
  };

  "redhat"."vscode-yaml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-yaml";
    publisher = "redhat";
    version = "1.14.0";
    sha256 = "0pww9qndd2vsizsibjsvscz9fbfx8srrj67x4vhmwr581q674944";
  };

  "github"."copilot" = vscode-utils.extensionFromVscodeMarketplace {
    name = "copilot";
    publisher = "github";
    version = "1.152.662";
    sha256 = "0gvc2prh10bgjpb0flnvaclj7n4s11myinvxid3phrh5x4jqxhwh";
  };

  "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
    name = "go";
    publisher = "golang";
    version = "0.40.1";
    sha256 = "0844kxbi7qi79wal0cqcd4wiygc42fyhamn33lsx2ms4yj5jxri9";
  };

  "gruntfuggly"."todo-tree" = vscode-utils.extensionFromVscodeMarketplace {
    name = "todo-tree";
    publisher = "gruntfuggly";
    version = "0.0.226";
    sha256 = "0yrc9qbdk7zznd823bqs1g6n2i5xrda0f9a7349kknj9wp1mqgqn";
  };

  "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-kubernetes-tools";
    publisher = "ms-kubernetes-tools";
    version = "1.3.15";
    sha256 = "1x6npc90p6b1wx5sd1hd0x0djahmffr6lw9cxh2zg10rbpq48w8i";
  };

  "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform";
    publisher = "hashicorp";
    version = "2.29.2024011611";
    sha256 = "0nmr0iyc9iifzf5wvqq501kwrsf9016iig613djjsykp3p2lja79";
  };

  "ionutvmi"."path-autocomplete" = vscode-utils.extensionFromVscodeMarketplace {
    name = "path-autocomplete";
    publisher = "ionutvmi";
    version = "1.25.0";
    sha256 = "0jjqh3p456p1aafw1gl6xgxw4cqqzs3hssr74mdsmh77bjizcgcb";
  };

  "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "even-better-toml";
    publisher = "tamasfe";
    version = "0.19.2";
    sha256 = "0q9z98i446cc8bw1h1mvrddn3dnpnm2gwmzwv2s3fxdni2ggma14";
  };

  "redhat"."ansible" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ansible";
    publisher = "redhat";
    version = "2.9.118";
    sha256 = "0yndj2r0w2zxc5firxgfrykkc5ajy9gsmrfmkz80kfhwk33n9y1p";
  };

  "vivaxy"."vscode-conventional-commits" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-conventional-commits";
    publisher = "vivaxy";
    version = "1.25.0";
    sha256 = "00mv34898y4xgqv6xf57bdl32qbbma4imz08jc4v5skmwjrgbwr8";
  };

  "fnando"."linter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "linter";
    publisher = "fnando";
    version = "0.0.19";
    sha256 = "13bllbxd7sy4qlclh37qvvnjp1v13al11nskcf2a8pmnmj455v4g";
  };

  "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc";
    publisher = "catppuccin";
    version = "3.11.0";
    sha256 = "12bzx1pv9pxbm08dhvl8pskpz1vg2whxmasl0qk2x54swa2rhi4d";
  };

  "mrmlnc"."vscode-json5" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-json5";
    publisher = "mrmlnc";
    version = "1.0.0";
    sha256 = "0bghvq89pp5s4liw11py8afyrlg4b02npv9ypnrnl0d2w99ab6aw";
  };

  "catppuccin"."catppuccin-vsc-icons" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc-icons";
    publisher = "catppuccin";
    version = "0.33.0";
    sha256 = "0kyx63q83w9yb10mnapd83q863dkzx8n8hdljrrl15ml5hhimk2i";
  };

  "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
    name = "nix-ide";
    publisher = "jnoortheen";
    version = "0.2.2";
    sha256 = "1264027sjh9a112si0y0p3pk3y36shj5b4qkpsj207z7lbxqq0wg";
  };

  "luisfontes19"."vscode-swissknife" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-swissknife";
    publisher = "luisfontes19";
    version = "1.8.1";
    sha256 = "1rpk8zayzkn2kg4jjdd2fy6xl50kib71dqg73v46326cr4dwxa7c";
  };

  "elagil"."pre-commit-helper" = vscode-utils.extensionFromVscodeMarketplace {
    name = "pre-commit-helper";
    publisher = "elagil";
    version = "0.5.0";
    sha256 = "05cs1ndnha9dgv1ys23z81ajk300wpixqmks0lfmrj1zwyjg2wlj";
  };

  "shipitsmarter"."sops-edit" = vscode-utils.extensionFromVscodeMarketplace {
    name = "sops-edit";
    publisher = "shipitsmarter";
    version = "1.0.0";
    sha256 = "0b2z9khiwrpf6gxdb9y315ayqkibvgixmvx82in5rlp8pndb6sq4";
  };
}
