# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.

{ pkgs }:

let
  vscode-utils = pkgs.vscode-utils;
in
{
  "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
    name = "python";
    publisher = "ms-python";
    version = "2024.3.10601007";
    sha256 = "09wvmgmqjn6620fknzdax9a6z2zcmyz20qjq24pya21cr2bb66gc";
  };

  "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-pylance";
    publisher = "ms-python";
    version = "2024.2.104";
    sha256 = "04fi5wqz34b8y94wb21dsfdcn5blxgwcdr4s5qa4apzm6yqgi6f9";
  };

  "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "prettier-vscode";
    publisher = "esbenp";
    version = "10.1.0";
    sha256 = "01s0vi2h917mqfpdrhqhp2ijwkibw95yk2js0l587wvajbbry2s9";
  };

  "ms-azuretools"."vscode-docker" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-docker";
    publisher = "ms-azuretools";
    version = "1.29.0";
    sha256 = "0rz32qwdf7a5hn3nnhxviaf8spwsszfrxmhnbbskspi5r9b6qm4r";
  };

  "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gitlens";
    publisher = "eamodio";
    version = "2024.2.2904";
    sha256 = "185q2wzwk9a65nxmyajscp888x925drpkdzral0x03yydwq172w1";
  };

  "ms-vscode-remote"."remote-containers" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-containers";
    publisher = "ms-vscode-remote";
    version = "0.330.0";
    sha256 = "19a24fszhhc6d40r5r2kh5kvmpg0614p0666cdzci4nn5qr4bh3g";
  };

  "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-ssh";
    publisher = "ms-vscode-remote";
    version = "0.108.2023112915";
    sha256 = "1ys59dys5kmijr9f2afbzbwm7dx7ps78jdwp89q1kb4c0aajmkx2";
  };

  "redhat"."vscode-yaml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-yaml";
    publisher = "redhat";
    version = "1.14.0";
    sha256 = "0pww9qndd2vsizsibjsvscz9fbfx8srrj67x4vhmwr581q674944";
  };

  "github"."copilot" = vscode-utils.extensionFromVscodeMarketplace {
    name = "copilot";
    publisher = "github";
    version = "1.168.742";
    sha256 = "1kp8myk7n42pfya5zgw7g0mw5ygdwrff5ank8ddsrby40vc455nd";
  };

  "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
    name = "go";
    publisher = "golang";
    version = "0.41.1";
    sha256 = "0i4h458x90v2bfr0la8axg6fs0756f2paby6h34pj4vflhi78axm";
  };

  "gruntfuggly"."todo-tree" = vscode-utils.extensionFromVscodeMarketplace {
    name = "todo-tree";
    publisher = "gruntfuggly";
    version = "0.0.226";
    sha256 = "0yrc9qbdk7zznd823bqs1g6n2i5xrda0f9a7349kknj9wp1mqgqn";
  };

  "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-kubernetes-tools";
    publisher = "ms-kubernetes-tools";
    version = "1.3.15";
    sha256 = "1x6npc90p6b1wx5sd1hd0x0djahmffr6lw9cxh2zg10rbpq48w8i";
  };

  "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform";
    publisher = "hashicorp";
    version = "2.30.2024022914";
    sha256 = "0raqzyvj69x6qkwbg2ypl30qag5rygisr6cw9h3hgiizj95cqhhy";
  };

  "ionutvmi"."path-autocomplete" = vscode-utils.extensionFromVscodeMarketplace {
    name = "path-autocomplete";
    publisher = "ionutvmi";
    version = "1.25.0";
    sha256 = "0jjqh3p456p1aafw1gl6xgxw4cqqzs3hssr74mdsmh77bjizcgcb";
  };

  "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "even-better-toml";
    publisher = "tamasfe";
    version = "0.19.2";
    sha256 = "0q9z98i446cc8bw1h1mvrddn3dnpnm2gwmzwv2s3fxdni2ggma14";
  };

  "redhat"."ansible" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ansible";
    publisher = "redhat";
    version = "2.12.143";
    sha256 = "1sfq4fkyxj1i0zk1rvyrlbrcfa6fchlv6f9rcslzc9h9asqpni9l";
  };

  "fnando"."linter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "linter";
    publisher = "fnando";
    version = "0.0.19";
    sha256 = "13bllbxd7sy4qlclh37qvvnjp1v13al11nskcf2a8pmnmj455v4g";
  };

  "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc";
    publisher = "catppuccin";
    version = "3.11.2";
    sha256 = "04xcl9vbd4spdy7bl35g0720qbhx11ym65afrjs50jg7ng1y28df";
  };

  "mrmlnc"."vscode-json5" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-json5";
    publisher = "mrmlnc";
    version = "1.0.0";
    sha256 = "0bghvq89pp5s4liw11py8afyrlg4b02npv9ypnrnl0d2w99ab6aw";
  };

  "catppuccin"."catppuccin-vsc-icons" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc-icons";
    publisher = "catppuccin";
    version = "1.9.1";
    sha256 = "04anq80m96ld9m8pljz1q051x6ryh49ldb10f550pwsswkfb3vhr";
  };

  "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
    name = "nix-ide";
    publisher = "jnoortheen";
    version = "0.2.2";
    sha256 = "1264027sjh9a112si0y0p3pk3y36shj5b4qkpsj207z7lbxqq0wg";
  };

  "luisfontes19"."vscode-swissknife" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-swissknife";
    publisher = "luisfontes19";
    version = "1.8.1";
    sha256 = "1rpk8zayzkn2kg4jjdd2fy6xl50kib71dqg73v46326cr4dwxa7c";
  };

  "elagil"."pre-commit-helper" = vscode-utils.extensionFromVscodeMarketplace {
    name = "pre-commit-helper";
    publisher = "elagil";
    version = "0.5.0";
    sha256 = "05cs1ndnha9dgv1ys23z81ajk300wpixqmks0lfmrj1zwyjg2wlj";
  };

  "shipitsmarter"."sops-edit" = vscode-utils.extensionFromVscodeMarketplace {
    name = "sops-edit";
    publisher = "shipitsmarter";
    version = "1.0.0";
    sha256 = "0b2z9khiwrpf6gxdb9y315ayqkibvgixmvx82in5rlp8pndb6sq4";
  };
}
